### ISSUE TITLE
Investigate memory leak warning

### ISSUE THREAD

**Issue by tomgreenfield** [adapt-security/adapt-authoring#163]
```console
(node:16576) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 moduleloaded listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
```

**Comment by taylortom** [comment]
Caused by most modules waiting for the logger (see [AbstractModule#log](https://github.com/adapt-security/adapt-authoring-core/blob/master/lib/abstractmodule.js#L81-L97)).

As the message suggests, we just need to raise the limit. The question is: to what? Would be nice to link this to a config value, but that'd require a bit of extra logic.

**Comment by taylortom** [comment]
Added a workaround for this here: https://github.com/adapt-security/adapt-authoring-core/commit/4d4670d281f97b399cbf55b400f996c95c57b1f8

Bit of a magic number, but have now allowed for 10 'moduleloaded' listeners per installed dependency, which should be more than enough (this includes nested dependencies i.e. deps of deps).

**Comment by taylortom** [comment]
Getting this one again

**Comment by taylortom** [comment]
_Hopefully_ finally killed this one once and for all by rewriting the `DependencyLoader#waitForModule` code to remove multiple `moduleloaded` listeners.

See https://github.com/adapt-security/adapt-authoring-core/commit/8b0ba0a2793bcdfa11889c21c0a153f6d0aa3b3d
