### ISSUE TITLE
npx at-confgen doesn't work

### ISSUE THREAD

**Issue by simondate** [adapt-security/adapt-authoring#490]
I've tried running this command to generate a AAT configuration file but nothing appears.

Nothing [appears in the registry](https://registry.npmjs.org/at-confgen), so I'm not sure if it's not set up yet or if I need to have some other script to run it as part of?

**Comment by taylortom** [comment]
Were you running this from the root of an existing install? Otherwise npx will try to pull it from GitHub (it's not a standalone tool atm, so that 404 type error is expected).

On a side-note: the script itself hadn't been updated to work with some recent changes, so have pushed a (hopefully) fixed version.

**Comment by simondate** [comment]
It's weird as the command works when you aren't in the repo.

I've not been able to get the installation working at the moment - I keep on getting npm errors for both headless and non-headless install.

![image](https://user-images.githubusercontent.com/1676635/153770801-3676a836-1025-473a-aedb-04043d649c8e.png)

Node version 16.13.1.

I'm assuming the script not working is as a result of this? Let me know if you need help testing! 😃

**Comment by taylortom** [comment]
Can't replicate this one.

For anyone attempting to test, you can run:
```bash
NODE_ENV=testing npx at-confgen
```
